version: '3.3'
services:
  app:
    image: aishwarya029/moviesdemo:latest
    restart: always
    ports:
     - '3000:3000'
    expose:
    - '3000'
  db:
    image: aishwarya029/moviesdemo_db:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'movies'
      MYSQL_USER: 'movietest'
      MYSQL_PASSWORD: '1qaz!QAZ'
      MYSQL_ROOT_PASSWORD: '1qaz!QAZ'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: